{
    # algorithm/tasks.py algbbands rand
    task: "run_algitem",
    kwargs: {
        opt: null,
        targets: ['bbands'],
        starttime: "datetime.utcnow() - timedelta(days=10)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        order: "random.sample([''.join(i) for i in list(itertools.product(['+','-'],['buy','sell','portfolio_value']))], random.randint(1,6))",
        limit: "random.randint(100, 200)",
        debug: False,
        cfg: {
            buf_win: 30
        }
    },
    description: "BBandsAlgorithm.__class__.__doc__" 
}