{
    task: collect_algitem,
    kwargs: {
        opt: null,
        targets: ['bbands'],
        starttime: datetime.utcnow() - timedelta(days=10),
        endtime: datetime.utcnow(),
        stockids: [],
        traderids: [],
        order: ['-buy', '-sell', '-portfolio_value'],
        limit: 100,
        debug: False,
        #atlast: ['buy>2', 'sell>3', 'portfolio_value']
        cfg: {
            buf_win: 30
        }
    },
    description: 'bbands algorithm'
}