{
    # algorithm/tasks.py algbbands rand layer 2
    task: "run_algitem",
    kwargs: {
        opt: null,
        targets: ['bbands'],
        starttime: "datetime.utcnow() - timedelta(days=10)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        reserved: False,
        constraint: "lambda x: x.value[\"portfolio\"] > 0",
        order: "lambda x: [-x.value[\"buys\"], -x.value[\"sells\"]]",
        callback: null,
        limit: "random.randint(100, 200)",
        debug: False,
        metadata: null,
        cfg: {
            buf_win: 30
        }
    },
    description: "BBandsAlgorithm.__class__.__doc__" 
}