{
    # algorithm/task.py
    task: run_algitem,
    kwargs: {
        opt: null,
        targets: ['btrader'],
        starttime: datetime.utcnow() - timedelta(days=10),
        endtime: datetime.utcnow(),
        stockids: [],
        traderids: [],
        order: ['-buy', '-sell', '-portfolio_value'],
        callback: null,
        limit: 100,
        debug: False,
        cfg: {
            buf_win: 30
        }
    },
    description: DualemaAlgorithm.__class.__.__doc__
}