{
    # algorithm/task.py layer 2
    task: "run_algitem",
    kwargs: {
        opt: null,
        targets: ['btrader'],
        starttime: "datetime.utcnow() - timedelta(days=10)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        constraint: "lambda x: x.value[\"totalportfolio\"] > 0",
        order: "lambda x: [-x.value[\"totalbuys\"], -x.value[\"totalsells\"]]",
        callback: null,
        limit: "random.randint(100, 200)",
        debug: False,
        cfg: {
            buf_win: 30
        }
    },
    description: "DualemaAlgorithm.__class.__.__doc__"
}