{
    # algorithm/tasks.py algbbands rand
    task: "run_algitem",
    kwargs: {
        opt: null,
        targets: ['bbands'],
        starttime: "datetime.utcnow() - timedelta(days=10)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        constraint: ,
        order: ,
        limit: "random.randint(100, 200)",
        debug: False,
        cfg: {
            buf_win: 30
        }
    },
    description: "BBandsAlgorithm.__class__.__doc__" 
}