{
    #algorithm/tasks.py
    task: "run_algitem",
    kwargs: {
        opt: null,
        targets: ['dualema'],
        starttime: "datetime.utcnow() - timedelta(days=60)",
        endtime: datetime.utcnow(),
        stockids: [],
        traderids: [],
        order: "['-buys', '-sells', '-portfolio_value']",
        callback: null,
        limit: 100,
        debug: False,
        cfg: {
            buf_win: 30,
            short_ema_win: 20,
            long_ema_win: 40,
            buy_amount: 100,
            sell_amount: 100
        }
    },
    description: "DualEMAAlgorithm.__class__.__doc__"
}