{
    #algorithm/tasks.py layer 2
    task: "run_algitem",
    kwargs: {
        opt: null,
        targets: ['dualema'],
        starttime: "datetime.utcnow() - timedelta(days=60)",
        endtime: datetime.utcnow(),
        stockids: [],
        traderids: [],
        reserved: False,
        constraint: "lambda x: x.value[\"portfolio\"] > 0",
        order: "lambda x: [-x.value[\"buys\"], -x.value[\"sells\"]]",
        callback: null,
        limit: "random.randint(100, 200)",
        debug: False,
        metadata: null,
        cfg: {
            buf_win: 30,
            short_ema_win: 20,
            long_ema_win: 40
        }
    },
    description: "DualEMAAlgorithm.__class__.__doc__"
}