{
    task: "collect_algitem",
    kwargs: {
        opt: null,
        targets: ['dualema', 'btrader', 'bbands'],
        starttime: null,
        endtime: null,
        stockids: [],
        traderids: [],
        reserved: False,
        base: 'stock',
        constraint": "lambda x: x.value[\"portfolio\"] > 0",
        order": "lambda x: [-x.value[\"buys\"], -x.value[\"sells\"]]",
        callback: null,
        limit: 50,
        debug: False,
        metadata: null
    },
    description: 'collect all algitem based on each leaf items'
}