{
    # handler/tasks.py hiscredit rand layer 1
    task: "collect_hisitem",
    kwargs: {
        opt: null,
        targets: ['credit'],
        starttime: "datetime.utcnow() - timedelta(days=10)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        base: 'stock',
        constraint: "lambda x: x.value[\"efinanceremain\"] > 0 or x.value[\"ebearfinaratio\"] > 0",
        order: "lambda x: [-x.value[\"ebearfinaratio\"], -x.value[\"totalfinanceremain\"]]",
        limit: "random.randint(100, 200)",
        debug: False
    },
    description: 'find best buy stockids based on credit collected constraint during this time period set'
}
