{
    task: collect_hisitem,
    kwargs: {
        opt: null,
        targets: ['stock', 'credit', 'future', 'trader'],
        starttime: null,
        endtime: null,
        stockids: [],
        traderids: [],
        base: 'stock',
        order: [],
        callback: null,
        limit: 50,
        debug: False
    },
    description: 'collect all hisitem based on each leaf items'
}
