{
    # handler/tasks.py layer 1
    # TODO: complete stockids
    task: "collect_hisitem",
    kwargs: {
        opt: null,
        targets: ['stock'],
        starttime: "datetime.utcnow() - timedelta(days=15)",
        endtime: "datetime.utcnow()",
        stockids: ['3474'],
        traderids: [],
        base: 'stock',
        constraint: null,
        order: null,
        callback: null,
        limit: 100,
        debug: False
    },
    description: '臺灣50指數成分股票'
}