{
    # handler/tasks.py hisstock rand layer 1
    task: "collect_hisitem",
    kwargs: {
        opt: null,
        targets: ['stock'],
        starttime: "datetime.utcnow() - timedelta(days=15)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        reserved: False,
        base: 'stock',
        constraint: "lambda x: x.value[\"eclose\"] > 0 and x.value[\"evolume\"] > 0",
        order: "lambda x: [-x.value[\"totalvolume\"], -x.value[\"eclose\"]]",
        callback: null,
        limit: "random.randint(100, 200)",
        debug: False,
        metadata: null
    },
    description: 'find best buy stockids based on stock collected constraint during this time period set'
}
