{
    # handler/tasks.py histrader rand
    task: "collect_hisitem",
    kwargs: {
        opt: null,
        targets: ['trader'],
        starttime: "datetime.utcnow() - timedelta(days=5)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        base: 'stock',
        constraint: "lambda x: x.value[\"ebuyratio\"] > 0 or x.value[\"totalbuyratio\"] > 0",
        order: "lambda x: [-x.value[\"totalvolume\"], -x.value[\"totalbuyratio\"]]",
        callback: null,
        limit: "random.randint(100, 200)",
        debug: False
        },
    description: 'find best buy stockids based on trader collected constraint during this time period set'
}
