{
    # handler/tasks.py
    task: collect_hisitem,
    kwargs: {
        opt: null,
        targets: ['trader'],
        starttime: datetime.utcnow() - timedelta(days=5),
        endtime: datetime.utcnow(),
        stockids: [],
        traderids: [],
        base: 'stock',
        order: ['-totalvolume', '-totalbuyvolume', '+totalsellvolume'],
        callback: null,
        limit: 100,
        debug: False
        },
    description: 'find best buy stockids based on trader collected constraint during this time period set'
}
