{
    #notify/tasks.py
    tasks: collect_notitem,
    kwargs: {
        opt: null,
        target: ['gmail'],
        starttime: datetime.utcnow() - timedelta(days=15),
        endtime: datetime.utcnow(),
        stockids: [],
        traderids: [],
        order: [],
        limit: 100,
        debug: False,
        cfg: {
            'GMAIL_ACCOUNT': 'funningboy2'
            'GMAIL_PASSWD': 'xxxx'
            'GMAIL_RCPT': [
                'funningboy@gmail.com',
                'funningboy2@gmail.com'
            ]
        }
    },
    description: 'email notify'
}