{
    #notify/tasks.py
    tasks: collect_notitem,
    kwargs: {
        opt: null,
        targets: ['gmail'],
        starttime: datetime.utcnow() - timedelta(days=15),
        endtime: datetime.utcnow(),
        stockids: [],
        traderids: [],
        limit: 100,
        debug: False,
        cfg: {
            'GMAIL_ACCOUNT': os.environ.get('GMAIL_ACCOUNT', 'null'),
            'GMAIL_PASSWD': os.environ.get('GMAIL_PASSWD', 'null'),
            'GMAIL_RCPT': [
                'funningboy@gmail.com'
            ]
        }
    },
    description: 'email notify'
}