{
    #notify/tasks.py
    task: "collect_ntyitem",
    kwargs: {
        opt: null,
        targets: ['gmail'],
        starttime: "datetime.utcnow() - timedelta(days=1)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        limit: 100,
        debug: False,
        cfg: {
            GMAIL_ACCOUNT: "os.environ.get('GMAIL_ACCOUNT', '')",
            GMAIL_PASSWD: "os.environ.get('GMAIL_PASSWD', '')",
            GMAIL_RCPT: [
                'funningboy@gmail.com'
            ]
        }
    },
    description: 'email notify'
}
