{
    #notify/tasks.py
    task: "collect_ntyitem",
    kwargs: {
        opt: null,
        targets: ['gmail', 'line'],
        starttime: "datetime.utcnow() - timedelta(days=15)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        order: [],
        limit: 100,
        debug: False,
        cfg: {
            GMAIL_ACCOUNT: "os.environ.get('GMAIL_ACCOUNT', '')",
            GMAIL_PASSWD: "os.environ.get('GMAIL_PASSWD', '')",
            GMAIL_RCPT: [
                'funningboy@gmail.com'
            ],
            LINE_ACCOUNT:  "os.environ.get('LINE_ACCOUNT', '')",
            LINE_PASSWD:  "os.environ.get('LINE_PASSWD', '')",
            LINE_GROUP: [
                'stock'
            ]
        }
    },
    description: 'notify all'
}
