{
    #notify/tasks.py
    task: "collect_ntyitem",
    kwargs: {
        opt: null,
        targets: ['line'],
        starttime: "datetime.utcnow() - timedelta(days=1)",
        endtime: "datetime.utcnow()",
        stockids: [],
        traderids: [],
        order: [],
        limit: 100,
        debug: False,
        cfg: {
            LINE_ACCOUNT: "os.environ.get('LINE_ACCOUNT', '')",
            LINE_PASSWD: "os.environ.get('LINE_PASSWD', '')",
            LINE_GROUP: [
                'stock'
            ]
        }
    },
    description: 'line notify'
}
